### ISSUE TITLE
Nimble install doesn't work

### ISSUE THREAD

**Issue by Clonkk** [yglukhov/asyncthreadpool#4]
After running ``nimble install asyncthreadpool`` and trying to compile a simple example I get the following error : 
``/home/rcaillaud/.nimble/pkgs/asyncthreadpool-0.1.0/asyncthreadpool.nim(2, 17) Error: cannot open file: ./private/pipes``

For reference, here's the content of the installed package in Nimble : 
```
✔ rcaillaud ~/Workspace/playground/asyncthreads$ ll ~/.nimble/pkgs/asyncthreadpool-0.1.0/
total 24
drwxr-xr-x   2 rcaillaud users 4096 Jul  7 09:06 ./
drwxr-xr-x 118 rcaillaud users 4096 Jul  7 09:06 ../
-rw-r--r--   1 rcaillaud users 7104 Jul  7 09:06 asyncthreadpool.nim
-rw-r--r--   1 rcaillaud users  170 Jul  7 09:06 asyncthreadpool.nimble
-rw-r--r--   1 rcaillaud users  198 Jul  7 09:06 nimblemeta.json
```

**Comment by yglukhov** [comment]
Will fix once #3 is merged, to avoid conflicts.
