### ISSUE TITLE
Should use of ``thread``/``gcsafe`` pragma be enforced ?

### ISSUE THREAD

**Issue by Clonkk** [yglukhov/asyncthreadpool#6]
Should this library enforce the use of ``gcsafe`` or ``thread`` - which to my understanding are mostly inter-changeable  nowadays - for proc that are ``spawn``'ed  ?

I'm curious what the consensus is on this.

**Comment by yglukhov** [comment]
`thread` pragma is not needed. The spawned proc will be executed in a thread-runner proc which is already `thread`.

`gcsafe` is enforced iirc.
